[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nested-runner"
version = "0.2.0"
description = "Self-hosted раннеры GitHub Actions внутри GitHub Actions"
readme = "README.md"
requires-python = ">=3.13"

[project.urls]
Homepage = "https://github.com/wprhvso/nested-runner"

[project.scripts]
nested-runner = "nested_runner.__main__:cli"

[tool.hatch.build.targets.wheel]
packages = ["nested_runner"]

[tool.hatch.build.targets.sdist]
include = ["nested_runner", "keys", "README.md", "VERSION"]
