[pytest]
addopts = -ra --strict-markers
pythonpath = .
xfail_strict = true

norecursedirs =
    .*
    *.egg
    venv
    build
    dist
    target
    result
    node_modules
    migrations
    packer
    terraform
    docker
    keys
    nix

asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
