name: ci

on:
  push:

jobs:
  ruff:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: ruff check --output-format github .

  format:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: ruff format --check --diff .

  pyright:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: uv sync --frozen
      - run: basedpyright

  pytest:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: uv sync --frozen
      - run: echo "$PWD/.venv/bin" >>"$GITHUB_PATH"
      - run: pytest

  flake:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: nix flake check -L
