name: test

on:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: [self-hosted]
    timeout-minutes: 5

    steps:
      - name: Where am I
        run: |
          echo "runner name: $RUNNER_NAME"
          echo "hostname:    $(hostname)"
          uname -a

      - name: Do something
        run: |
          echo "matryoshka works"
          sleep 5
